apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: myDeployApp
  type: NodePort
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3000
      nodePort: 30391
