apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "value-helm-demo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "value-helm-demo.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "value-helm-demo.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          ports:
            - containerPort: 3000
